# Generated by Django 5.0.3 on 2024-05-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.CharField(default='Event Manager', max_length=200),
        ),
    ]
