# Generated by Django 5.0.3 on 2024-04-16 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tag Name', max_length=200)),
                ('events', models.ManyToManyField(blank=True, to='myapi.event')),
            ],
        ),
    ]
