# Generated by Django 5.0.3 on 2024-04-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='tags', to='myapi.event'),
        ),
    ]
