# Generated by Django 5.0.3 on 2024-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapi', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='managed_events',
            field=models.ManyToManyField(blank=True, related_name='managed_events', to='myapi.event'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='Customers', to='myapi.event'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='Customer_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='Customer_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='Organizers', to='myapi.event'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='Organizer_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='Organizer_user_permissions', to='auth.permission'),
        ),
    ]
