# Generated by Django 5.0.3 on 2024-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapi', '0005_alter_customer_groups_alter_organizer_groups_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='group',
            name='organizers',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group Name', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='auth.permission'),
        ),
    ]
