# Generated by Django 5.0.3 on 2024-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapi', '0006_remove_group_customers_remove_group_organizers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizer',
            new_name='User',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='myapi.user'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
