# Generated by Django 5.0.4 on 2024-04-18 19:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_tag_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, default='Organizer Bio', null=True),
        ),
    ]
