# Generated by Django 5.0.4 on 2024-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_organizer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
