# Generated by Django 5.0.4 on 2024-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_alter_organizer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='company',
            field=models.CharField(blank=True, default='Organizer Company', max_length=200, null=True),
        ),
    ]
