# Generated by Django 5.0.4 on 2024-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_organizer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
